### PR TITLE
update children based on props update

### PR DESCRIPTION
**Pull request by jdeanquin-dg**
Update content based on dynamic children

### CODE REVIEW

**Comment by jdeanquin-dg** [comment]
hello @gl0gl0 would you have time to take a look at this pr?

Thank you!

**Comment by gl0gl0** [comment]
Hi @jdeanquin-dg! Thanks for taking the time to do this! :) I'll merge this PR to develop to do some testing first, and then release it, but looking good! ;)

**Comment by gl0gl0** [comment]
Hi @jdeanquin-dg
I was doing a quick test with the update, but not all props seem to be working appropriately yet. This is the test I did:
`import React, { Component } from 'react';
import InfiniteCarousel from '../src/index';

class Test extends Component {
  constructor(props) {
    super(props);

    // initial state
    this.state = {
      children: this.getInitialChildren(),
    };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        children: this.getOtherChildren(),
      });
    }, 20000);
  }

  getInitialChildren = () => [
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
  ];

  getOtherChildren = () => [
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
    <div>
      
    </div>,
  ];

  render() {
    const { children } = this.state;
    return (
      <InfiniteCarousel
        swipe
        autoCycle
        lazyLoad
        dots
        paging
        showSides
        breakpoints={[
          {
            breakpoint: 768,
            settings: {
              slidesToScroll: 2,
              slidesToShow: 2,
            },
          },
          {
            breakpoint: 1200,
            settings: {
              slidesToScroll: 3,
              slidesToShow: 3,
            },
          },
        ]}
        sideSize={0.1}
        sidesOpacity={0.5}
        slidesToScroll={4}
        slidesToShow={4}
        onNextClick={() => {}}
        onPreviousClick={() => {}}
      >
        {children}
      </InfiniteCarousel>
    );
  }
}

Test.propTypes = {};

Test.defaultProps = {};

export default Test;
`

As first glance the automatic cycle and pagination seem messed up, probably need to do some re-setup of some other properties as well after updating the `children` prop

**Comment by jdeanquin-dg** [comment]
Thanks for testing, I will take a look and provide a fix.

**Pull request merged**
